package br.com.marksr.pointercontrol;

import br.com.marksr.pointercontrol.commons.GenericPublisher;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marcos
 */
public class ControlScreen extends javax.swing.JFrame {
    private GenericPublisher<MouseEventInterface, MouseEventPack> mouseListeners;
    private GenericPublisher<ClosingEventInterface, Void> closingEventListeners;
    private int diffX = 0;
    private int diffY = 0;
    
    /**
     * Creates new form ControllScreen
     */
    public ControlScreen() {
        initComponents();
        
        mouseListeners = new GenericPublisher<MouseEventInterface, MouseEventPack>() {

            @Override
            public void action(MouseEventInterface l, MouseEventPack d) {
                switch (d.type) {
                    case MouseEventPack.MOUSE_MOVE:
                        l.mouseMove(d.point);
                        break;
                    case MouseEventPack.MOUSE_CLICK:
                        l.mouseClick(d.point);
                        break;
                    case MouseEventPack.MOUSE_DRAG:
                        l.mouseDrag(d.point);
                        break;
                    case MouseEventPack.MOUSE_DOWN:
                        l.mouseDown(d.point);
                        break;
                    case MouseEventPack.MOUSE_UP:
                        l.mouseUp(d.point);
                        break;
                }
            }
        };
        
        closingEventListeners = new GenericPublisher<ClosingEventInterface, Void>() {

            @Override
            public void action(ClosingEventInterface l, Void d) {
                l.closing();
            }
        };
    }
    
    public void setOnMouseMoveEvent(MouseEventInterface event) {
        mouseListeners.setOnEvent(event);
    }

    public void removeOnMouseMoveEvent(MouseEventInterface event) {
        mouseListeners.removeOnEvent(event);
    }
    
    public void setOnClosingEvent(ClosingEventInterface event) {
        closingEventListeners.setOnEvent(event);
    }

    public void removeOnClosingEvent(ClosingEventInterface event) {
        closingEventListeners.removeOnEvent(event);
    }    
    
    void setWindowSize(Integer width, Integer height) {
        setSize(width, height);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
//        Point p = new Point(evt.getX(), evt.getY());
//        mouseListeners.fire(p);
        
    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
//        System.out.println("Moved: "+evt.getPoint().toString()+ " " + jPanel2.getBounds().toString());
        mouseListeners.fire(new MouseEventPack(MouseEventPack.MOUSE_MOVE, evt.getPoint()));
    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        mouseListeners.fire(new MouseEventPack(MouseEventPack.MOUSE_CLICK, evt.getPoint()));
    }//GEN-LAST:event_jPanel2MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closingEventListeners.fire(null);
    }//GEN-LAST:event_formWindowClosing

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
//        System.out.println("Dragged: "+evt.getPoint().toString()+ " " + jPanel2.getBounds().toString());
        mouseListeners.fire(new MouseEventPack(MouseEventPack.MOUSE_DRAG, evt.getPoint()));
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        System.out.println("Pressed: "+evt.getPoint().toString()+ " " + jPanel2.getBounds().toString());
        mouseListeners.fire(new MouseEventPack(MouseEventPack.MOUSE_DOWN, evt.getPoint()));
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        System.out.println("Released: "+evt.getPoint().toString()+ " " + jPanel2.getBounds().toString());
        mouseListeners.fire(new MouseEventPack(MouseEventPack.MOUSE_UP, evt.getPoint()));
    }//GEN-LAST:event_jPanel2MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public interface ClosingEventInterface {
        public void closing();
    }

    public interface MouseEventInterface {
        void mouseMove(Point point);
        void mouseClick(Point point);
        void mouseDrag(Point point);
        void mouseDown(Point point);
        void mouseUp(Point point);
    }

    public class MouseEventPack {
        public static final int MOUSE_MOVE = 0;
        public static final int MOUSE_CLICK = 1;
        public static final int MOUSE_DRAG = 2;
        public static final int MOUSE_UP = 3;
        public static final int MOUSE_DOWN = 4;
        public final int type;
        public final Point point;

        public MouseEventPack(int type, Point point) {
            this.type = type;
            this.point = point;
        }
    }
}
